//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITST.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BillReceiptList
    {
        public int ListID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy hh:mm:ss tt}")]
        public Nullable<System.DateTime> DateCreate { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy hh:mm:ss tt}")]
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string SerialNumber { get; set; }
        public string Cause { get; set; }
        public string Type { get; set; }
        public string Model { get; set; }
        public string Brand { get; set; }
        public string Plant { get; set; }
        public string Department { get; set; }
        public string Location { get; set; }
        public string Phase { get; set; }
        public string MachineName { get; set; }
        public string UserName { get; set; }
        public string DeviceName { get; set; }

        [DisplayFormat(DataFormatString = "{0:0,0.00}")]
        //[DisplayFormat(DataFormatString = "{0:#,##0.000#}", ApplyFormatInEditMode = true)]
        public Nullable<double> Price { get; set; }
        public Nullable<int> Unit { get; set; }
        public string FixAccess { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy hh:mm:ss tt}")]
        public Nullable<System.DateTime> InRepairDate { get; set; }
        public string BillReceiptType { get; set; }
        public string BillReceiptNo { get; set; }
        public string CompanyName { get; set; }
    }
}
