//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITST.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class BillReceipt
    {
        public int BillReceiptID { get; set; }
        public string Type { get; set; }
        public string BillReceiptNo { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> IsPrint { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy hh:mm:ss tt}")]
        public Nullable<System.DateTime> DateCreate { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy hh:mm:ss tt}")]
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
    }
}
