//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITST.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Brand
    {
        public Brand()
        {
            this.Devices = new HashSet<Device>();
            this.Models = new HashSet<Model>();
        }
    
        public int BrandID { get; set; }

        [Required(ErrorMessage = "BrandName Required")]
        public string BrandName { get; set; }
        public string Description { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual ICollection<Device> Devices { get; set; }
        public virtual ICollection<Model> Models { get; set; }
    }
}
