//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITST.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Device
    {
        public int DeviceID { get; set; }
        public Nullable<int> MachineID { get; set; }
        public Nullable<int> UMachineID { get; set; }
        public string DeviceName { get; set; }
        public string Description { get; set; }
        public bool IsAsset { get; set; }
        public bool IsNotPR { get; set; }
        public string CauseRequistion { get; set; }

        public double PricePerItem { get; set; }

        [Required(ErrorMessage = "SerialNumber Required")]
        public string SerialNumber { get; set; }
        public string Specification { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> PlantID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> DeviceTypeID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> ModelID { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy hh:mm:ss tt}")]
        public Nullable<System.DateTime> DateCreate { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy hh:mm:ss tt}")]
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public string Reason { get; set; }
        public string BillReceiptNo { get; set; }

        //[Required(ErrorMessage = "LocationStock Required")]
        public Nullable<int> LocationStockID { get; set; }

        [Required(ErrorMessage = "LocationStock Required")]
        public string LocationStockName { get; set; }
        public string CurrentLocation { get; set; }
        public string MacAddress { get; set; }

        [Required(ErrorMessage = "ModelName Required")]
        public string ModelName { get; set; }
        public string Type { get; set; }
        public string UserName { get; set; }
        public string UserName2 { get; set; }
        public string UserName3 { get; set; }
        public string UserName4 { get; set; }
        public string MachineName { get; set; }
        public string BrandName { get; set; }
        public string StatusName { get; set; }
        public Nullable<System.DateTime> InstockDate { get; set; }
        public Nullable<int> PhaseID { get; set; }
        public string PhaseName { get; set; }
        public string PRNumber { get; set; }
        public string FixAccess { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> UserID { get; set; }
        public bool Confirm { get; set; }
        public string PreSerialNumber { get; set; }
        public string PreIPAddress { get; set; }
        public string Uri { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public string PhoneNumber3 { get; set; }
        public string PhoneNumber4 { get; set; }

        //[Required(ErrorMessage = "BillReceiptID Required")]
        public Nullable<int> BillReceiptID { get; set; }

        public virtual Brand Brand { get; set; }
        public virtual Department Department { get; set; }
        public virtual DeviceType DeviceType { get; set; }
        public virtual Location Location { get; set; }
        public virtual Machine Machine { get; set; }
        public virtual Model Model { get; set; }
        public virtual Plant Plant { get; set; }
        public virtual Status Status { get; set; }
        public virtual UserMachine UserMachine { get; set; }
        public virtual User User { get; set; }
    }
}
