//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITST.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class IntExtPhone
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Location Required")]
        public string LocationName { get; set; }

        [Required(ErrorMessage = "PhoneNumber Required")]
        public string PhoneNumber { get; set; }

        [Required(ErrorMessage = "Type Required")]
        public string Type { get; set; }
    }
}
