//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITST.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITStockEntities1 : DbContext
    {
        public ITStockEntities1()
            : base("name=ITStockEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<DeviceType> DeviceTypes { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocationStock> LocationStocks { get; set; }
        public virtual DbSet<Machine> Machines { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<Phase> Phases { get; set; }
        public virtual DbSet<Plant> Plants { get; set; }
        public virtual DbSet<PMSheet> PMSheets { get; set; }
        public virtual DbSet<RecordInRepair> RecordInRepairs { get; set; }
        public virtual DbSet<RecordRequisition> RecordRequisitions { get; set; }
        public virtual DbSet<RecordSale> RecordSales { get; set; }
        public virtual DbSet<RecordSpare> RecordSpares { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserMachine> UserMachines { get; set; }
        public virtual DbSet<RecordReinstock> RecordReinstocks { get; set; }
        public virtual DbSet<RecordDevice> RecordDevices { get; set; }
        public virtual DbSet<RecordInstock> RecordInstocks { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<BillReceipt> BillReceipts { get; set; }
        public virtual DbSet<BillReceiptList> BillReceiptLists { get; set; }
        public virtual DbSet<UserSheet> UserSheets { get; set; }
        public virtual DbSet<IntExtPhone> IntExtPhones { get; set; }
        public virtual DbSet<SerialNumberGenerate> SerialNumberGenerates { get; set; }
        public virtual DbSet<SerialNumberTemplate> SerialNumberTemplates { get; set; }
        public virtual DbSet<LimitDeviceQuantity> LimitDeviceQuantities { get; set; }
    }
}
