//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITST.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Machine
    {
        public Machine()
        {
            this.Devices = new HashSet<Device>();
        }
    
        public int MachineID { get; set; }

        [StringLength(50, MinimumLength = 5, ErrorMessage = "Maximum Length is 50 char, Minimum Length is 5 char")]
        public string MachineName { get; set; }
        public string Description { get; set; }
        public Nullable<int> PlantID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<int> PhaseID { get; set; }
        public string IPAddress { get; set; }
        public string PLCAddress { get; set; }
        public string MACAddress { get; set; }
        public string FormerMachineName { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<Device> Devices { get; set; }
        public virtual Location Location { get; set; }
        public virtual Phase Phase { get; set; }
        public virtual Plant Plant { get; set; }
    }
}
