//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITST.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Model
    {
        public Model()
        {
            this.Devices = new HashSet<Device>();
        }

        public int ModelID { get; set; }

        [Required(ErrorMessage = "ModelName Required")]
        public string ModelName { get; set; }

        [Required(ErrorMessage = "DeviceType Required")]
        public Nullable<int> DeviceTypeID { get; set; }

        [Required(ErrorMessage = "Brand Required")]
        public Nullable<int> BrandID { get; set; }

        public string Specification { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> IsAccess { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }

        public virtual Brand Brand { get; set; }
        public virtual ICollection<Device> Devices { get; set; }
        public virtual DeviceType DeviceType { get; set; }
    }
}
