//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITST.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Phase
    {
        public Phase()
        {
            this.Machines = new HashSet<Machine>();
        }
    
        public int PhaseID { get; set; }

        [Required(ErrorMessage = "PhaseName Required")]
        public string PhaseName { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreate { get; set; }
        public System.DateTime DateUpdate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual ICollection<Machine> Machines { get; set; }
    }
}
