//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITST.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PMSheet
    {
        public int SheetID { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string PCBoardBrand { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string PCBoardModel { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string PCBoardSerial { get; set; }

        public string PCBoardRemark { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string ProcessorBrand { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string ProcessorModel { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string ProcessorSerial { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string ProcessorRemark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string MemoryBrand { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string MemoryModel { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string MemorySerial { get; set; }

        public string MemoryRemark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string VideoCardBrand { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string VideoCardModel { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string VideoCardSerial { get; set; }

        public string VideoCardRemark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string LANCardBrand { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string LANCardSerial { get; set; }

        [StringLength(30, ErrorMessage = "Maximum Length is 30 char")]
        public string LANCardModel { get; set; }

        public string LANCardRemark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string MouseBrand { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string MouseModel { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string MouseSerial { get; set; }

        public string MouseRemark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string MonitorBrand { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string MonitorModel { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string MonitorSerial { get; set; }

        public string MonitorRemark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string KeyboardBrand { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string KeyboardModel { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string KeyboardSerial { get; set; }

        public string KeyboardRemark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string ScannerBrand { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string ScannerModel { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string ScannerSerial { get; set; }

        public string ScannerRemark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string DVDBrand { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string DVDModel { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string DVDSerial { get; set; }

        public string DVDRemark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string HDD1Brand { get; set; }

        [StringLength(30, ErrorMessage = "Maximum Length is 30 char")]
        public string HDD1Model { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string HDD1Serial { get; set; }

        public string HDD1Remark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string HDD2Brand { get; set; }

        [StringLength(30, ErrorMessage = "Maximum Length is 30 char")]
        public string HDD2Model { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string HDD2Serial { get; set; }

        public string HDD2Remark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string PrinterBrand { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string PrinterModel { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string PrinterSerial { get; set; }

        public string PrinterRemark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string UPSBrand { get; set; }

        [StringLength(30, ErrorMessage = "Maximum Length is 30 char")]
        public string UPSModel { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string UPSSerial { get; set; }

        public string UPSRemark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string PCICardBrand { get; set; }

        [StringLength(30, ErrorMessage = "Maximum Length is 30 char")]
        public string PCICardModel { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string PCICardSerial { get; set; }

        public string PCIRemark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string BluetoothBrand { get; set; }

        [StringLength(30, ErrorMessage = "Maximum Length is 30 char")]
        public string BluetoothModel { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string BluetoothSerial { get; set; }

        public string BluetoothRemark { get; set; }

        [StringLength(30, ErrorMessage = "Maximum Length is 30 char")]
        public string HUBBrand { get; set; }

        [StringLength(30, ErrorMessage = "Maximum Length is 30 char")]
        public string HUBModel { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string HUBSerial { get; set; }

        public string HUBRemark { get; set; }

        [StringLength(30, ErrorMessage = "Maximum Length is 20 char")]
        public string OtherHardwareBrand { get; set; }

        [StringLength(30, ErrorMessage = "Maximum Length is 20 char")]
        public string OtherHardwareModel { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string OtherHardwareSerial { get; set; }

        public string OtherHardwareRemark { get; set; }

        [StringLength(30, ErrorMessage = "Maximum Length is 30 char")]
        public string OtherHardware1Brand { get; set; }

        [StringLength(30, ErrorMessage = "Maximum Length is 30 char")]
        public string OtherHardware1Model { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string OtherHardware1Serial { get; set; }

        public string OtherHardware1Remark { get; set; }

        [StringLength(30, ErrorMessage = "Maximum Length is 30 char")]
        public string OtherHardware2Brand { get; set; }

        [StringLength(30, ErrorMessage = "Maximum Length is 30 char")]
        public string OtherHardware2Model { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string OtherHardware2Serial { get; set; }

        public string OtherHardware2Remark { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string FixAccess { get; set; }

        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<int> PlantID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> PhaseID { get; set; }
        public Nullable<int> MachineID { get; set; }
        public string PlantName { get; set; }
        public string DepartmentName { get; set; }
        public string LocationName { get; set; }
        public string PhaseName { get; set; }
        public string MachineName { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string Zip7Version { get; set; }

        public string Zip7Remark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string AcrobatVersion { get; set; }

        public string AcrobatRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string CureGraphVersion { get; set; }

        public string CureGraphRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string JP1Version { get; set; }

        public string JP1Remark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string MSOfficeVersion { get; set; }

        public string MSOfficeRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string OracleVersion { get; set; }

        public string OracleRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string RaidVersion { get; set; }

        public string RaidRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string SeedWincsVersion { get; set; }

        public string SeedWincsRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string SharedCPCVersion { get; set; }

        public string SharedCPCRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string SharedDPanelPCVersion { get; set; }

        public string SharedDPanelPCRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string TightVNCVersion { get; set; }

        public string TightVNCRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string TrendMicroVersion { get; set; }

        public string TrendMicroRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string WindowsVersion { get; set; }

        public string WindowsRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 15 char")]
        public string OtherSoftware { get; set; }

        public string OtherSoftwareRemark { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string OtherHardwareName1 { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string OtherHardwareName2 { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string OtherHardwareName3 { get; set; }
    }
}
