//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITST.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class RecordDevice
    {
        public int EdeviceID { get; set; }
        public string Description { get; set; }
        public string EditBy { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy hh:mm:ss tt}")]
        public Nullable<System.DateTime> EditDate { get; set; }
        public string SerialNumber { get; set; }
        public string Model { get; set; }
        public string Type { get; set; }
        public string Brand { get; set; }
        public string Specification { get; set; }
        public string Plant { get; set; }
        public string Department { get; set; }
        public string Location { get; set; }
        public string Phase { get; set; }
        public string Machine { get; set; }
        public string Status { get; set; }
        public string LocationStock { get; set; }
        public string UserName { get; set; }
        public string DeviceName { get; set; }
        public string Cause { get; set; }
    }
}
