//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserMachines = new HashSet<UserMachine>();
            this.Devices = new HashSet<Device>();
        }
    
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmployeeID { get; set; }
        public string Position { get; set; }
        public string Section { get; set; }
        public string Phone { get; set; }
        public int DepartmentID { get; set; }
        public int LocationID { get; set; }
        public int PlantID { get; set; }
        public string UserLogOn { get; set; }
        public string IPAddress { get; set; }
        public string MacAddress { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<int> PhaseID { get; set; }
        public string PhaseName { get; set; }
        public string FullName { get; set; }
        public string DeviceName { get; set; }
        public string NickName { get; set; }
        public string PreviousUri { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Location Location { get; set; }
        public virtual Plant Plant { get; set; }
        public virtual ICollection<UserMachine> UserMachines { get; set; }
        public virtual ICollection<Device> Devices { get; set; }
    }
}
