//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMachine
    {
        public UserMachine()
        {
            this.Devices = new HashSet<Device>();
        }
    
        public int UMachineID { get; set; }
        public int UserID { get; set; }
        public string ComputerName { get; set; }
        public string UserLogon { get; set; }
        public int DepartmentID { get; set; }
        public int PlantID { get; set; }
        public int LocationID { get; set; }
        public string MACAddress { get; set; }
        public string PLCAddress { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<Device> Devices { get; set; }
        public virtual Location Location { get; set; }
        public virtual Plant Plant { get; set; }
        public virtual User User { get; set; }
    }
}
