//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITST.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UserSheet
    {
        public int SheetID { get; set; }

        [StringLength(30, ErrorMessage = "Maximum Length is 30 char")]
        public string PCBoardBrand { get; set; }

        [StringLength(30, ErrorMessage = "Maximum Length is 30 char")]
        public string PCBoardModel { get; set; }

        public string PCBoardSerial { get; set; }
        public string PCBoardRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string ProcessorBrand { get; set; }

        [StringLength(30, ErrorMessage = "Maximum Length is 30 char")]
        public string ProcessorModel { get; set; }
        public string ProcessorSerial { get; set; }
        public string ProcessorRemark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string MemoryBrand { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string MemoryModel { get; set; }
        public string MemorySerial { get; set; }
        public string MemoryRemark { get; set; }

        [StringLength(30, ErrorMessage = "Maximum Length is 30 char")]
        public string VideoCardBrand { get; set; }

        [StringLength(50, ErrorMessage = "Maximum Length is 50 char")]
        public string VideoCardModel { get; set; }
        public string VideoCardSerial { get; set; }
        public string VideoCardRemark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string LANCardBrand { get; set; }

        [StringLength(30, ErrorMessage = "Maximum Length is 30 char")]
        public string LANCardModel { get; set; }

        public string LANCardSerial { get; set; }
        public string LANCardRemark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string MouseBrand { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string MouseModel { get; set; }
        public string MouseSerial { get; set; }
        public string MouseRemark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string MonitorBrand { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string MonitorModel { get; set; }
        public string MonitorSerial { get; set; }
        public string MonitorRemark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string Monitor2Brand { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string Monitor2Model { get; set; }
        public string Monitor2Serial { get; set; }
        public string Monitor2Remark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string KeyboardBrand { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string KeyboardModel { get; set; }
        public string KeyboardSerial { get; set; }
        public string KeyboardRemark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string ScannerBrand { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string ScannerModel { get; set; }
        public string ScannerSerial { get; set; }
        public string ScannerRemark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string DVDBrand { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string DVDModel { get; set; }
        public string DVDSerial { get; set; }
        public string DVDRemark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string HDD1Brand { get; set; }

        [StringLength(30, ErrorMessage = "Maximum Length is 30 char")]
        public string HDD1Model { get; set; }
        public string HDD1Serial { get; set; }
        public string HDD1Remark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string HDD2Brand { get; set; }

        [StringLength(30, ErrorMessage = "Maximum Length is 30 char")]
        public string HDD2Model { get; set; }
        public string HDD2Serial { get; set; }
        public string HDD2Remark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string PrinterBrand { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string PrinterModel { get; set; }
        public string PrinterSerial { get; set; }
        public string PrinterRemark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string UPSBrand { get; set; }

        [StringLength(30, ErrorMessage = "Maximum Length is 30 char")]
        public string UPSModel { get; set; }
        public string UPSSerial { get; set; }
        public string UPSRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string Zip7Ver { get; set; }
        public string Zip7Remark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string AcrobatVer { get; set; }
        public string AcrobatRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string AutoCADVer { get; set; }
        public string AutoCADRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string CureGraphVer { get; set; }
        public string CureGraphRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string CutePDFVer { get; set; }
        public string CutePDFRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string HealthBookVer { get; set; }
        public string HealthBookRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string HRMSystemVer { get; set; }
        public string HRMSystemRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string IllustratorVer { get; set; }
        public string IllustratorRemark { get; set; }

        [StringLength(25, ErrorMessage = "Maximum Length is 25 char")]
        public string JP1Ver { get; set; }
        public string JP1Remark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string LexitronDictVer { get; set; }
        public string LexitronDictRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string MiniTabVer { get; set; }
        public string MiniTabRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string MSOfficeVer { get; set; }
        public string MSOfficeRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string PhotoShopVer { get; set; }
        public string PhotoShopRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string SAPVer { get; set; }
        public string SAPRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string SaveToPDFVer { get; set; }
        public string SaveToPDFRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string SeedWincsVer { get; set; }
        public string SeedWincsRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string SolidEdgeVer { get; set; }
        public string SolidEdgeRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string TrendMicroVer { get; set; }
        public string TrendMicroRemark { get; set; }

        [StringLength(15, ErrorMessage = "Maximum Length is 15 char")]
        public string WindowsVer { get; set; }
        public string WindowsRemark { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string ZimbraVer { get; set; }
        public string ZimbraRemark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string OtherProgram { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string OtherProgramVer { get; set; }
        public string OtherProgramRemark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string OtherProgram1 { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string OtherProgram1Ver { get; set; }
        public string OtherProgram1Remark { get; set; }

        [StringLength(20, ErrorMessage = "Maximum Length is 20 char")]
        public string OtherProgram2 { get; set; }

        [StringLength(10, ErrorMessage = "Maximum Length is 10 char")]
        public string OtherProgram2Ver { get; set; }
        public string OtherProgram2Remark { get; set; }
        public Nullable<int> UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> PlantID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> PhaseID { get; set; }
        public string Plant { get; set; }
        public string Department { get; set; }
        public string Location { get; set; }
        public string Phase { get; set; }
        public string FixAccess { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string DeviceName { get; set; }
    }
}
